# -*- coding: utf-8 -*-
"""Emit sql/43_cohort_funnel.sql - why the cohorts differ in size.

The window list appears in two separate tagging CTEs in the output. Declaring
it twice by hand is how two copies drift apart, so it is declared once here.

    python3 tools/gen_funnel_sql.py
    python3 tools/gen_funnel_sql.py --check
"""
import io, os, re, sys

BAR  = 1_700_000      # the production bar: 170,000 Toman in Rial
BARS = [800000, 1000000, 1200000, 1400000, 1700000, 2000000, 2400000]

# name, feature months, label months (4 or none), what it is
WINDOWS = [
    ("A_140301_140306", (140301, 140306), (140307, 140310),
     "TRAIN - months 1-6 of 1403"),
    ("B_140401_140406", (140401, 140406), (140407, 140410),
     "VALID - months 1-6 of 1404"),
    ("C_140501_140506", (140501, 140506), None,
     "SCORE - months 1-6 of 1405, no label, the outcome is the future"),
    ("D_140407_140412", (140407, 140412), (140501, 140504),
     "ANCHOR - the old VALID, measured at 0.95 pct in 41_forward_horizons.sql"),
    ("E_140307_140312", (140307, 140312), (140401, 140404),
     "SEASON CONTROL - a second window whose LABEL lands on months 1-4"),
]

def tag_expr(col, spans, indent):
    """Nested IF mapping a month_key to its window name."""
    pad = " " * indent
    out = []
    for nm, (lo, hi) in spans:
        out.append(f"IF({col} BETWEEN {lo} AND {hi}, '{nm}',")
    body = f"\n{pad}".join(out)
    return body + "\n" + pad + "   NULL" + ")" * len(spans)

def label_span_expr():
    """A literal naming each window's label span, so D5 shows the season."""
    parts = [f"IF(win = '{n}', '{l[0]}_{l[1]}'," for n, _, l, _ in WINDOWS if l]
    pad = " " * 8
    return ("\n" + pad).join(parts) + "\n" + pad + "   'none'" + ")" * len(parts)

FEAT = [(n, f) for n, f, _, _ in WINDOWS]
LAB  = [(n, l) for n, _, l, _ in WINDOWS if l]
FEAT_LO = min(f[0] for _, f in FEAT); FEAT_HI = max(f[1] for _, f in FEAT)
LAB_LO  = min(l[0] for _, l in LAB);  LAB_HI  = max(l[1] for _, l in LAB)

def check_disjoint(spans, what):
    for i in range(len(spans)):
        for j in range(i + 1, len(spans)):
            a, b = spans[i][1], spans[j][1]
            if a[0] <= b[1] and b[0] <= a[1]:
                raise SystemExit(f"{what} spans overlap: "
                                 f"{spans[i][0]} and {spans[j][0]}")
check_disjoint(FEAT, "feature")
check_disjoint(LAB, "label")

HEADER = f"""-- ============================================================================
--  WHY DO THE COHORTS DIFFER IN SIZE?                       (Trino/Presto)
--
--  GENERATED by tools/gen_funnel_sql.py - do not hand-edit. The window list
--  is used by two separate tagging expressions below and is declared once in
--  that script, because two hand-maintained copies drift apart.
--
--  THE PROBLEM. TRAIN at 140301..140306 returned 3,733,333 subscribers
--  against the 6,879,803 measured at 140407..140412 on the SAME screen - a
--  46 pct shortfall. The row count is not the worry: 3.7M rows at a 0.95 pct
--  rate is about 35,000 bads, which is ample to fit on. The worry is whether
--  it is the same KIND of population that SCORE holds.
--
--  TWO CANDIDATE CAUSES, WITH DIFFERENT FIXES, so guessing is not enough:
--
--    1 NOMINAL DRIFT. The screen's 170,000 Toman bar is FIXED NOMINAL, and
--      nominal revenue per subscriber rises with inflation and tariff
--      changes. The same bar is therefore a HARSHER screen the further back
--      the window sits, selecting the richer tail.
--          fix: a per-window bar. 42_model_datasets.sql COHORT_BAR takes one,
--               and D3 below measures what it should be.
--
--    2 COVERAGE. Thin or ramping data in the earliest months. This base has
--      already produced one loading gap, where debt_scr and suspend_scr were
--      all zero in 6 of 10 months and read as a PSI of 13.89.
--          fix: none. Those months are unusable at any bar, and TRAIN has to
--               move - accepting a seasonal mismatch instead.
--
--  D1 and D2 separate them. Smooth upward drift in every revenue percentile
--  from A to C is cause 1. Fewer subscribers present, or a spike in NULL
--  arpu rather than genuinely low revenue, is cause 2.
--
--  FOUR WINDOWS. A, B and C are the three cohorts, year-over-year aligned on
--  months 1-6. D is the window the 0.95 pct figure was measured on.
--
{chr(10).join(f"--      {n:16s} features {f[0]}..{f[1]}  "
              + (f"label {l[0]}..{l[1]}" if l else "no label      ")
              + f"  {d}" for n, f, l, d in WINDOWS)}
--
--  D IS THE CORRECTNESS ANCHOR. Its screened population should come back near
--  6,879,803 and its event rate near 0.95 pct, because that is exactly what
--  41_forward_horizons.sql measured on that window. If D reproduces those two
--  numbers, this file agrees with 41 and its figures for A, B and C can be
--  trusted. If D does NOT reproduce them, debug this file before reading
--  anything else in it.
--
--  A vs B vs C is the YEAR effect at constant season (all months 1-6).
--  B vs D is the SEASON effect within one year (months 1-6 against 7-12).
--  Those two together say how much of the gap is inflation and how much is
--  the calendar.
--
--  NO percent character anywhere. NO CASE expressions.
-- ============================================================================

DROP TABLE IF EXISTS dwbi_temp40_db.dcb_funnel;
CREATE TABLE dwbi_temp40_db.dcb_funnel WITH (format='PARQUET') AS
WITH sm AS (
    -- One row per subscriber per month, flattened BEFORE any window tag is
    -- attached. Aggregating a multi-row-per-key relation after a join is how
    -- this project once read revenue as 8,000,000 instead of 2,000,000.
    SELECT   sbrp_id, month_key,
             SUM(COALESCE(arpu,0) - COALESCE(tot_arpu_tax_amt,0)) AS rev,
             MAX(IF(sbrp_stat_id = 3, 1, 0))                      AS ow,
             MAX(IF(sbrp_stat_id = 4, 1, 0))                      AS tw,
             SUM(IF(arpu IS NULL, 1, 0))                          AS n_null
    FROM     dwbi_fact_db.v_fact_sbrp_mthly_cip
    WHERE    month_key BETWEEN {FEAT_LO} AND {FEAT_HI}
      AND    sbrp_typ_id = 1
    GROUP BY sbrp_id, month_key
),
tagged AS (
    -- A month_key can sit in one window's FEATURE span and another window's
    -- LABEL span. Those are resolved in separate CTEs, so there is no clash.
    SELECT  sm.*,
            {tag_expr("month_key", FEAT, 12)} AS win
    FROM    sm
),
fw AS (
    SELECT   sbrp_id, win,
             COUNT(*)                        AS n_months,
             SUM(IF(rev >= {BAR}, 1, 0))     AS rev_months,
             MAX(ow)                         AS ow_any,
             MAX(tw)                         AS tw_any,
             SUM(n_null)                     AS n_arpu_null,
             SUM(rev)                        AS rev_total
    FROM     tagged
    WHERE    win IS NOT NULL
    GROUP BY sbrp_id, win
),
lb AS (
    -- Presence here is what each cohort's INNER JOIN requires, so it belongs
    -- in the funnel. The tag is computed in a SUBQUERY so GROUP BY names a
    -- real column: Trino does not reliably group by a SELECT alias, and two
    -- copies of a nested IF drift apart.
    SELECT   sbrp_id, win,
             MAX(IF(sbrp_stat_id = 4, 1, 0)) AS y,
             COUNT(DISTINCT month_key)       AS n_label_months
    FROM (
        SELECT  sbrp_id, month_key, sbrp_stat_id,
                {tag_expr("month_key", LAB, 16)} AS win
        FROM    dwbi_fact_db.v_fact_sbrp_mthly_cip
        WHERE   month_key BETWEEN {LAB_LO} AND {LAB_HI}
          AND   sbrp_typ_id = 1
    ) q
    WHERE    win IS NOT NULL
    GROUP BY sbrp_id, win
)
SELECT      f.sbrp_id, f.win, f.n_months, f.rev_months, f.ow_any, f.tw_any,
            f.n_arpu_null, f.rev_total, l.y, l.n_label_months
FROM        fw f
LEFT JOIN   lb l ON l.sbrp_id = f.sbrp_id AND l.win = f.win
;

-- ---------------------------------------------------------------------------
-- D1  THE FUNNEL. Where subscribers are lost, window by window.
--
--     Read ACROSS: present -> cleared the revenue bar -> never one-way ->
--     never two-way -> judgeable. If A and C differ mainly at pass_rev, the
--     bar is the cause. If they differ at present, it is coverage.
-- ---------------------------------------------------------------------------
SELECT  win,
        COUNT(*)                                                  AS present,
        AVG(CAST(n_months AS DOUBLE))                             AS avg_months_seen,
        SUM(IF(rev_months >= 2, 1, 0))                            AS pass_rev,
        SUM(IF(rev_months >= 2 AND ow_any = 0, 1, 0))             AS pass_rev_ow,
        SUM(IF(rev_months >= 2 AND ow_any = 0 AND tw_any = 0, 1, 0))
                                                                  AS screened,
        SUM(IF(rev_months >= 2 AND ow_any = 0 AND tw_any = 0
               AND n_label_months IS NOT NULL, 1, 0))             AS cohort_rows,
        100.0 * SUM(IF(rev_months >= 2, 1, 0)) / COUNT(*)         AS pass_rev_pct
FROM     dwbi_temp40_db.dcb_funnel
GROUP BY win
ORDER BY win;

-- ---------------------------------------------------------------------------
-- D2  INFLATION OR COVERAGE? Revenue per subscriber-month, by window.
--
--     Inflation is a smooth upward march in EVERY percentile from A to C.
--     A coverage gap is the same distribution shape with fewer subscribers
--     in it, or a spike in avg_null_arpu_rows rather than genuinely low
--     revenue. The bar is 1,700,000 Rial - watch where it falls in each
--     window's distribution, because that IS the drift in one number.
-- ---------------------------------------------------------------------------
SELECT  win,
        COUNT(*)                                                 AS subs,
        AVG(rev_total / NULLIF(n_months, 0))                     AS mean_rev_per_month,
        APPROX_PERCENTILE(rev_total / NULLIF(n_months, 0), 0.25)  AS p25,
        APPROX_PERCENTILE(rev_total / NULLIF(n_months, 0), 0.50)  AS p50,
        APPROX_PERCENTILE(rev_total / NULLIF(n_months, 0), 0.75)  AS p75,
        APPROX_PERCENTILE(rev_total / NULLIF(n_months, 0), 0.90)  AS p90,
        100.0 * SUM(IF(rev_total / NULLIF(n_months, 0) >= {BAR}, 1, 0))
              / COUNT(*)                                         AS pct_avg_month_over_bar,
        AVG(CAST(n_arpu_null AS DOUBLE))                         AS avg_null_arpu_rows
FROM     dwbi_temp40_db.dcb_funnel
GROUP BY win
ORDER BY win;

-- ---------------------------------------------------------------------------
-- D3  THE EQUALIZING BAR. Which bar admits the same SHARE of subscribers in
--     an earlier window as {BAR:,} admits in C (SCORE)?
--
--     Find C's pass_pct at {BAR:,}, then read down the A rows for the bar
--     whose pass_pct matches it. That bar is what COHORT_BAR['TRAIN'] should
--     be in 42_model_datasets.sql, and the same for B and VALID. The ratio
--     between them is the nominal drift, measured rather than assumed.
--
--     Its OWN table, not a query over the one above: CTEs do not survive
--     their statement, and the per-month revenue needed to re-test other
--     bars is not in dcb_funnel - only the count at the single fixed bar is.
-- ---------------------------------------------------------------------------
DROP TABLE IF EXISTS dwbi_temp40_db.dcb_funnel_bars;
CREATE TABLE dwbi_temp40_db.dcb_funnel_bars WITH (format='PARQUET') AS
WITH sm AS (
    SELECT   sbrp_id, month_key,
             SUM(COALESCE(arpu,0) - COALESCE(tot_arpu_tax_amt,0)) AS rev
    FROM     dwbi_fact_db.v_fact_sbrp_mthly_cip
    WHERE    month_key BETWEEN {FEAT_LO} AND {FEAT_HI}
      AND    sbrp_typ_id = 1
    GROUP BY sbrp_id, month_key
),
tagged AS (
    SELECT  sbrp_id, rev,
            {tag_expr("month_key", FEAT, 12)} AS win
    FROM    sm
),
per AS (
    SELECT      t.win, t.sbrp_id, b.bar,
                SUM(IF(t.rev >= b.bar, 1, 0)) AS months_at_bar
    FROM        tagged t
    CROSS JOIN  UNNEST(ARRAY[{", ".join(str(b) for b in BARS)}]) AS b (bar)
    WHERE       t.win IS NOT NULL
    GROUP BY    t.win, t.sbrp_id, b.bar
)
SELECT   win, bar,
         COUNT(*)                                             AS present,
         SUM(IF(months_at_bar >= 2, 1, 0))                    AS pass_2plus,
         100.0 * SUM(IF(months_at_bar >= 2, 1, 0)) / COUNT(*) AS pass_pct
FROM     per
GROUP BY win, bar
;

SELECT   bar, win, present, pass_2plus, pass_pct
FROM     dwbi_temp40_db.dcb_funnel_bars
ORDER BY bar, win;

-- ---------------------------------------------------------------------------
-- D4  THE GAP IN ONE TABLE. Each window's pass share at the fixed bar,
--     against C (SCORE). Large negative pp_vs_score for A and B means the
--     fixed bar is selecting the richer tail in the earlier windows, and
--     COHORT_BAR must be set from D3 before fitting.
-- ---------------------------------------------------------------------------
SELECT   win,
         pass_pct                                        AS pass_pct_at_fixed_bar,
         pass_pct - (SELECT pass_pct FROM dwbi_temp40_db.dcb_funnel_bars
                     WHERE bar = {BAR} AND win = 'C_140501_140506')
                                                         AS pp_vs_score,
         pass_2plus
FROM     dwbi_temp40_db.dcb_funnel_bars
WHERE    bar = {BAR}
ORDER BY win;

-- ---------------------------------------------------------------------------
-- D5  THE EVENT RATE PER WINDOW - the figure of record for each cohort.
--
--     CHECK D FIRST. Window D should come back near 6,879,803 screened at
--     about 0.95 pct, because that is what 41_forward_horizons.sql measured
--     on it. If it does, this file is consistent with 41 and the A and B
--     rates below are the numbers 42_model_datasets.sql T4 should be checked
--     against. If D is off, fix this file before trusting A and B.
--
--     A and B are the new TRAIN and VALID windows. Their rates have never
--     been measured before, which is precisely why T4 must not be compared
--     against the 0.95 pct figure - that belongs to D.
-- ---------------------------------------------------------------------------
SELECT  win,
        {label_span_expr()}                                    AS label_span,
        COUNT(*)                                             AS screened,
        SUM(y)                                               AS n_bad,
        100.0 * SUM(y) / NULLIF(COUNT(*), 0)                 AS bad_pct,
        SUM(IF(n_label_months >= 4, 1, 0))                   AS n_fully_observed,
        100.0 * SUM(IF(n_label_months >= 4, y, 0))
              / NULLIF(SUM(IF(n_label_months >= 4, 1, 0)), 0) AS bad_pct_full
FROM    dwbi_temp40_db.dcb_funnel
WHERE   rev_months >= 2
  AND   ow_any = 0
  AND   tw_any = 0
  AND   n_label_months IS NOT NULL
GROUP BY win, {label_span_expr()}
ORDER BY win;

-- ---------------------------------------------------------------------------
-- D6  SEASON OR YEAR? The grid, now that there are five windows.
--
--     MEASURED on the first run, before window E existed:
--
--       pass share at the fixed bar, months 1-6:  12.0 (1403) -> 14.6 (1404)
--                                                 -> 24.4 (1405)
--       so the fixed nominal bar admits TWICE the share of the base in 1405
--       that it did in 1403. The screen has loosened on its own.
--
--       event rate: 1403 m7-10 label 0.5730 pct, 1404 m7-10 label 0.5541 pct,
--       1405 m1-4 label 0.9492 pct. The first two agree closely while sitting
--       at DIFFERENT screen breadths (12.0 and 14.6 pct), so breadth is not
--       what moves the rate. The third differs mainly in LABEL SEASON and is
--       1.68x higher.
--
--     WINDOW E IS THE CONTROL FOR THAT CLAIM. The 1.68x rests on a single
--     observation of a months 1-4 label. E's label is 140401..140404, also
--     months 1-4, in a different year. If E comes back near 0.95 pct the
--     seasonal reading holds; if E comes back near 0.56 pct it does not, and
--     the D figure is about 1405 specifically rather than about the season.
-- ---------------------------------------------------------------------------
SELECT   win,
         bar,
         present,
         pass_2plus,
         pass_pct
FROM     dwbi_temp40_db.dcb_funnel_bars
WHERE    bar = {BAR}
ORDER BY win;
"""

def selfcheck(sql):
    nc = re.sub(r"--[^\n]*", "", sql)
    bad = []
    if "%" in nc: bad.append("percent character")
    if nc.count("(") != nc.count(")"): bad.append("unbalanced parentheses")
    if re.search(r"\bCASE\b", nc, re.I): bad.append("CASE expression")
    if any(ord(c) > 127 for c in nc): bad.append("non-ascii")
    ctes = set(re.findall(r"(?:WITH|,|\n)\s*(\w+)\s+AS\s*\(", nc))
    for i, st in enumerate(nc.split(";")):
        if not st.strip(): continue
        own  = set(re.findall(r"(?:WITH|,|\n)\s*(\w+)\s+AS\s*\(", st))
        refs = set(re.findall(r"(?:FROM|JOIN)\s+([A-Za-z_]\w*)\b", st))
        for r in refs & ctes:
            if r not in own:
                bad.append(f"statement {i} references CTE '{r}' it does not define")
    return bad

if __name__ == "__main__":
    problems = selfcheck(HEADER)
    if problems:
        print("SELF-CHECK FAILED:"); [print("  -", p) for p in problems]
        sys.exit(1)
    out = os.path.normpath(os.path.join(os.path.dirname(__file__), "..",
                                        "sql", "43_cohort_funnel.sql"))
    if "--check" in sys.argv:
        same = io.open(out, encoding="utf-8").read() == HEADER
        print(f"{out}: {'matches' if same else 'DIFFERS'}")
        sys.exit(0 if same else 1)
    io.open(out, "w", encoding="utf-8").write(HEADER)
    print(f"wrote {out}  ({len(HEADER.splitlines())} lines)")
    print("self-check passed: no percent, balanced parens, no CASE, ascii only,")
    print("feature spans disjoint, label spans disjoint, no unreachable CTEs")
